name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container: docker://hexpm/erlang:23.1.1-alpine-3.12.0
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_PASSWORD: postgres
        ports: ['5432:5432']
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2.0.0
      - run: echo "PATH=$PATH:`pwd`/bin" >> $GITHUB_ENV
      - run: apk add curl tar
      - name: Install gleam
        run: |
          GLEAM_VERSION=0.12.0-rc3 eval 'curl -Lo bin/gleam.tar.gz "https://github.com/gleam-lang/gleam/releases/download/v$GLEAM_VERSION/gleam-v$GLEAM_VERSION-linux-amd64.tar.gz"'
          tar -xf bin/gleam.tar.gz -C bin
          rm bin/gleam.tar.gz
      - name: Install rebar3
        run: |
          curl -Lo bin/rebar3 https://s3.amazonaws.com/rebar3/rebar3
          chmod +x bin/rebar3
      - run: gleam format --check src test
      - run: rebar3 install_deps
      - run: rebar3 eunit
